### ISSUE TITLE
SQL Syntax error if user is not authenticated

### ISSUE THREAD

**Issue by Afterster** [Grimthorr/laravel-user-settings#12]
Thanks for this, I'm gonna to use it.
But if current visitor is not authenticated and using Setting::get, generated SQL query will be invalid by default (`settings` from `users` where id = limit 1`). Wouldn't it be better / cleaner to always return default value in that case? This would avoid redundant if (Auth::check()) tests...

Thank you!

**Comment by EmadAdly** [comment]
hi Afterster
Make sure You put the route inside middleware web because to handle auth .

```
Route::group(['middleware' => 'web'], function () {

});
```

**Comment by johannesschobel** [comment]
Hey @Afterster ,
the problem is, that you need to retrieve the settings from the configured `(default_)constraint_value` configured in `laravel_user_settings.php` config file.

This is, by default, the `users` table - and the current `user` object! However, if you are not authenticated, it is questionable where to get the data from. As the main idea of this package is to add a user-specific setting to one object (i.e., a `user`) you don't have a "default value". For example, one user may have a setting variable `receiveEMails`, while another one may have a `language` variable in his configuration.

If you would like to have some kind of global configuration it is - at least in my opinion - not in the scope of this plugin. However, it may be possible to add further configuration tags (e.g., `default_config_language = en;` to an config file.

Hope this helps,
Cheers

**Comment by Grimthorr** [comment]
Thanks @EmadAdly & @johannesschobel for picking this up. I'll agree that this package is mostly for use for authenticated users. If you want to use it for guests you'll need some way to store settings for a visitor, which could get messy as it's hard to tell if this visitor will return.

However, you're right that if the visitor is not authenticated then returning with the default value would be helpful. I'll take a look to see if this can be pulled in.

**Comment by Grimthorr** [comment]
Upon further thought, I think authentication checks should be handled outside of the package and thus returning the default value when not authenticated may lead to confusion and/or inconsistencies. Please see my comment on #21.
